 # config file version
apiVersion: 1


 # list of datasources to insert/update depending
 # on what's available in the datbase
datasources:
   # <string, required> name of the datasource. Required
   # Used by the panels of the dashboards
 - name: infrabox 
   # <string, required> datasource type. Required
   type: postgres
   # <string, required> access mode. direct or proxy. Required
   access: proxy 
   # <int> org id. will default to orgId 1 if not specified
   orgId: 1
   # <string> url
   url: IP:port
   # <string> database name, if used
   database: 
   # <bool> enable/disable basic auth
   basicAuth: false
   # <bool> mark as default datasource. Max one per org
   isDefault: true
   # <map> fields that will be converted to json and stored in json_data
   jsonData:
       sslmode: disable
   #   graphiteVersion: "1.1"
   #   tlsAuth: true
   #   tlsAuthWithCACert: true
   ## <string> json object of data that will be encrypted.
   secureJsonData:
        #<string> database password, if used
        password:  
        #<string> database user, if used
        user: 
   #  tlsCACert: "..."
   #  tlsClientCert: "..."
   #  tlsClientKey: "..."
   version: 1
   # <bool> allow users to edit datasources from the UI.
   editable: true


 - name: prometheus
   # <string, required> datasource type. Required
   type: prometheus
   # <string, required> access mode. direct or proxy. Required
   access: proxy
   # <int> org id. will default to orgId 1 if not specified
   orgId: 1
   # <string> url
   url: http://IP:port
   version: 1
   editable: true 
