kind: Service
apiVersion: v1
metadata:
    name: infrabox-api
    namespace: {{ template "system_namespace" . }}
    labels:
        app: infrabox-api
spec:
    selector:
        app: infrabox-api
    ports:
    -
        name: http-web
        protocol: TCP
        port: 8080
        targetPort: 8080
