apiVersion: v1
kind: Secret
metadata:
  name: infrabox-admin
  namespace: {{ template "system_namespace" . }}
type: Opaque
data:
  email: {{ required "admin.email is required" .Values.admin.email | b64enc }}
  password: {{ required "admin.password is required" .Values.admin.password | b64enc }}
