{{ if .Values.storage.azure.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: infrabox-azure-credentials
  namespace: {{ template "system_namespace" . }}
type: Opaque
data:
  account-name: {{ required "storage.azure.account_name is required" .Values.storage.azure.account_name | b64enc }}
  account-key: {{ required "storage.azure.account_key is required" .Values.storage.azure.account_key | b64enc }}
{{ end }}
