{{ if or .Values.ha.enabled .Values.monitoring.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: infrabox-checker
  namespace: {{ template "system_namespace" . }}
type: Opaque
data:
{{ if .Values.ha.checker_slack_hook }}
  slack_hook_url: {{ .Values.ha.checker_slack_hook | b64enc }}
{{ end }}
{{ end }}