{{ if .Values.github.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: infrabox-github
  namespace: {{ template "system_namespace" . }}
type: Opaque
data:
  client_id: {{ required "github.client_id is required" .Values.github.client_id | b64enc }}
  client_secret: {{ required "github.client_secret is required" .Values.github.client_secret | b64enc }}
  webhook_secret: {{ required "github.webhook_secret is required" .Values.github.webhook_secret | b64enc }}
{{ end }}
