{{ if .Values.account.ldap.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: infrabox-ldap
  namespace: {{ template "system_namespace" . }}
type: Opaque
data:
  dn: {{ required "account.ldap.dn is required" .Values.account.ldap.dn | b64enc }}
  password: {{ required "account.ldap.password is required" .Values.account.ldap.password | b64enc }}
{{ end }}
