apiVersion: v1
kind: Secret
metadata:
  name: infrabox-rsa
  namespace: {{ template "system_namespace" . }}
type: Opaque
data:
  id_rsa: {{ .Values.admin.private_key }}
  id_rsa.pub: {{ .Values.admin.public_key }}
