{{ if .Values.storage.s3.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: infrabox-s3-credentials
  namespace: {{ template "system_namespace" . }}
type: Opaque
data:
  accessKey: {{ required "storage.s3.access_key_id is required" .Values.storage.s3.access_key_id | b64enc }}
  secretKey: {{ required "storage.s3.secret_access_key is required" .Values.storage.s3.secret_access_key | b64enc }}
{{ end }}
