{{ if .Values.monitoring.enabled }}
kind: Service
apiVersion: v1
metadata:
    name: infrabox-grafana
    namespace: {{ template "system_namespace" . }}
    labels:
        app: infrabox-grafana
spec:
    selector:
        app: infrabox-grafana
    ports:
    -
        name: http-web
        protocol: TCP
        port: 80
        targetPort: 80
{{ end }}
