apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gcp
  template:
    metadata:
      labels:
        name: gcp
    spec:
      containers:
        - name: gcp
          image: 192.168.1.31:5000/infrabox/service-gcp
          command:
          - gcp
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
