{{ if .Values.database.cloudsql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: infrabox-cloudsql-instance-credentials
type: Opaque
data:
  credentials.json: {{ .Values.database.cloudsql.service_account }}
{{ end }}
