apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: infrabox
spec:
    rules:
    -
        host: {{ .Values.host }}
        http:
            paths:
            -
                path: /*
                backend:
                    serviceName: infrabox-cluster-status
                    servicePort: 8080
