apiVersion: v1
kind: Secret
metadata:
  name: infrabox-postgres
type: Opaque
data:
{{ if .Values.database.postgres.enabled }}
  username: {{ required "database.postgres.username is required" .Values.database.postgres.username | b64enc }}
  password: {{ required "database.postgres.password is required" .Values.database.postgres.password | b64enc }}
{{ end }}
{{ if .Values.database.cloudsql.enabled }}
  username: {{ required "database.cloudsql.username is required" .Values.database.cloudsql.username | b64enc }}
  password: {{ required "database.cloudsql.password is required" .Values.database.cloudsql.password | b64enc }}
{{ end }}
