apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ibpipelineinvocations.core.infrabox.net
spec:
  group: core.infrabox.net
  names:
    kind: IBPipelineInvocation
    listKind: IBPipelineInvocationList
    plural: ibpipelineinvocations
    singular: ibpiplineinvocation
  scope: Namespaced
  version: v1alpha1
