{{ if .Values.github.enabled }}
kind: Service
apiVersion: v1
metadata:
    name: infrabox-github-trigger
    namespace: {{ template "system_namespace" . }}
    labels:
        app: infrabox-github-trigger
spec:
    selector:
        app: infrabox-github
    ports:
    -
        name: http-web
        protocol: TCP
        port: 8080
        targetPort: 8080
{{ end }}
